const L=window.LORE;
const routes=['home','map','factions','legions','chapters','worlds','characters','organizations','arsenal','timeline','detail'];
const labels={home:'ГЛАВНАЯ',map:'КАРТА ГАЛАКТИКИ',factions:'ФРАКЦИИ',legions:'ЛЕГИОНЫ',chapters:'ОРДЕНА АСТАРТЕС',worlds:'МИРЫ И РЕГИОНЫ',characters:'ПЕРСОНАЖИ',organizations:'ОРГАНИЗАЦИИ',arsenal:'ТЕХНИКА И ОРУЖИЕ',timeline:'ХРОНОЛОГИЯ'};
const collections={character:L.characters,legion:L.legions,chapter:L.chapters||[],faction:L.factions,location:L.locations,event:L.events,organization:L.organizations,arsenal:L.arsenal};
const byId=(arr,id)=>arr?.find(x=>x.id===id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

function setRoute(route,updateHash=true){
 if(!routes.includes(route))route='home';
 document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));
 document.getElementById(route).classList.add('active-page');
 document.querySelectorAll('[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===route));
 document.getElementById('currentSection').textContent=labels[route]||'ARCHIVE RECORD';
 document.body.classList.remove('menu-open');
 if(updateHash&&route!=='detail')history.pushState(null,'','#'+route);
 if(route==='map')setTimeout(fitMap,40);
 window.scrollTo({top:0,behavior:'smooth'});
}
function getRecord(type,id){return collections[type]?byId(collections[type],id):null}
function openDetail(type,id,updateHash=true){const o=getRecord(type,id);if(!o)return;renderDetail(type,o);setRoute('detail',false);document.getElementById('currentSection').textContent=o.name.toUpperCase();if(updateHash)history.pushState(null,'',`#${type}/${id}`)}
function parseHash(){const raw=location.hash.replace('#','');if(raw.includes('/')){const [t,id]=raw.split('/');if(getRecord(t,id)){openDetail(t,id,false);return}}setRoute(routes.includes(raw)?raw:'home',false)}
window.addEventListener('popstate',parseHash);
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){e.preventDefault();setRoute(r.dataset.route);return}const d=e.target.closest('[data-detail]');if(d){e.preventDefault();openDetail(d.dataset.detail,d.dataset.id);return}});
document.getElementById('mobileMenu').onclick=()=>document.body.classList.toggle('menu-open');

function sourceLinks(s=[]){return s.map(([n,u])=>`<a href="${esc(u)}" target="_blank" rel="noreferrer">${esc(n)} ↗</a>`).join('')}
function relationLabel(type,id){const o=getRecord(type,id);return o?.name||id}
function relationLinks(conns=[]){return conns.filter(([t,id])=>getRecord(t,id)).map(([t,id,label])=>`<a class="relation-link" href="#${t}/${id}" data-detail="${t}" data-id="${id}"><span>${esc(label||relationLabel(t,id))}</span><b>→</b></a>`).join('')}
function findRelations(type,o){
 const rel=[];const push=(t,id,label)=>{if(getRecord(t,id)&&!rel.some(x=>x[0]===t&&x[1]===id))rel.push([t,id,label])};
 (o.connections||[]).forEach(x=>push(...x));
 if(type==='character'){if(o.legion)push('legion',o.legion,byId(L.legions,o.legion)?.name);if(o.chapter)push('chapter',o.chapter,byId(L.chapters,o.chapter)?.name);if(o.faction)push('faction',o.faction,byId(L.factions,o.faction)?.name)}
 if(type==='legion'){if(o.primarch)push('character',o.primarch,byId(L.characters,o.primarch)?.name);L.characters.filter(c=>c.legion===o.id&&c.id!==o.primarch).slice(0,12).forEach(c=>push('character',c.id,c.name));(L.chapters||[]).filter(c=>c.parentLegion===o.id).slice(0,16).forEach(c=>push('chapter',c.id,c.name));}
 if(type==='chapter'){if(o.parentLegion)push('legion',o.parentLegion,byId(L.legions,o.parentLegion)?.name);L.characters.filter(c=>c.chapter===o.id).slice(0,16).forEach(c=>push('character',c.id,c.name));}
 if(type==='faction')L.characters.filter(c=>c.faction===o.id).slice(0,12).forEach(c=>push('character',c.id,c.name));
 // Reverse links: any record explicitly pointing at the current one becomes related too.
 for(const [t,arr] of Object.entries(collections)) for(const r of arr){
   if(r.id===o.id&&t===type)continue;
   if((r.connections||[]).some(x=>x[0]===type&&x[1]===o.id))push(t,r.id,r.name);
   if(type==='location'&&(r.home||'').toLowerCase().includes((o.name||'').toLowerCase()))push(t,r.id,r.name);
 }
 return rel.slice(0,28);
}
function expFor(type,o){return window.EXPANDED_LORE?.[type]?.[o.id]||null}
function assetFor(type,o){
 const special=window.SPECIFIC_ART?.[`${type}:${o.id}`];if(special)return special;
 const ex=expFor(type,o);if(ex?.hero)return ex.hero;
 if(type==='character'){
  if(o.id==='guilliman')return'/assets/guilliman-hero.jpg';
  if(o.faction==='chaos'||['abaddon','ahriman','kharn','typhus','lucius','huron'].includes(o.id)||String(o.status||'').toLowerCase().includes('демон'))return'/assets/chaos-rift.jpg';
  if(String(o.type||'').toLowerCase().includes('примарх'))return'/assets/primarchs.jpg';
  if(['gazghkull','ghazghkull','makari'].includes(o.id))return'/assets/orks-war.webp';
  if(['shadowsun','farsight','aunva'].includes(o.id))return'/assets/tau-empire.webp';
  if(['trazyn','orikan','imotekh','szeras','szarekh'].includes(o.id))return'/assets/trazyn-hero.webp';
  if(['eldrad','yvraine','vected','lelith'].includes(o.id))return'/assets/galaxy-map.jpg';
  return'/assets/imperium-city.jpg';
 }
 if(type==='legion')return o.allegiance==='traitor'?'/assets/chaos-rift.jpg':'/assets/primarchs.jpg';
 if(type==='chapter'){if(o.parentLegion==='ultramarines')return'/assets/guilliman-hero.jpg';if(o.parentLegion==='blood-angels')return'/assets/sanguinius-hero.webp';if(o.parentLegion==='dark-angels')return'/assets/lion-hero.webp';if(o.id==='carcharodons'||o.id==='minotaurs')return'/assets/imperium-city.jpg';return'/assets/primarchs.jpg';}
 if(type==='faction'){if(o.id==='orks')return'/assets/orks-war.webp';if(o.id==='tyranids'||o.id==='genestealer-cults')return'/assets/tyranids-war.webp';if(o.id==='tau')return'/assets/tau-empire.webp';if(o.id==='necrons')return'/assets/trazyn-hero.webp';return o.group==='Chaos'?'/assets/chaos-rift.jpg':o.group==='Xenos'?'/assets/galaxy-map.jpg':'/assets/imperium-city.jpg';}
 if(type==='location'){const n=(o.name||'').toLowerCase(),id=o.id||'';if(id==='terra')return'/assets/terra-panorama.webp';if(id==='macragge'||id==='ultramar')return'/assets/macragge-panorama.webp';if(id==='commorragh')return'/assets/drukhari-commorragh.webp';if(/craftworld|ulthwe|iyanden|biel|saim|alaitoc/.test(id+n))return'/assets/aeldari-craftworld.webp';if(/mars|ryza|graia|agripinaa|forge/.test(id+n))return'/assets/mechanicus-forge.webp';if(/tau|vi-orla|farsight|damocles|taros/.test(id+n))return'/assets/tau-sept.webp';if(/baal/.test(id+n))return'/assets/sanguinius-hero.webp';if(o.affiliation==='chaos'||o.type==='anomaly'||/rift|eye-of-terror|разлом|око ужаса/.test(id+n))return'/assets/great-rift-panorama.webp';return'/assets/galaxy-atlas.webp'}
 if(type==='event'){const n=(o.name||'').toLowerCase();if(/макраг|ультрамар|калт/.test(n))return'/assets/ultramarines-parade.webp';if(/баал|тира|улей|кракен|левиафан/.test(n))return'/assets/tyranid-invasion.webp';if(/армагед|орк|октари/.test(n))return'/assets/orks-apocalypse.webp';if(/тау|дамокл|тарос/.test(n))return'/assets/tau-sept.webp';if(/кади|разлом|ерес|хаос|чум|готи/.test(n))return'/assets/great-rift-panorama.webp';return'/assets/galaxy-atlas.webp'};
 if(type==='organization'){const h=JSON.stringify(o).toLowerCase();if(/орк|goff|evil sun|bad moon|deathskull|blood axe|snakebite/.test(h))return'/assets/orks-apocalypse.webp';if(/улей|tyranid|behemoth|kraken|leviathan|kronos|gorgon|jormungandr/.test(h))return'/assets/tyranid-invasion.webp';if(/aeldari|craftworld|ulth|iyanden|biel|saim|alaitoc/.test(h))return'/assets/aeldari-craftworld.webp';if(/drukhari|коммор/.test(h))return'/assets/drukhari-commorragh.webp';if(/тау|t’au|t'au|sept|farsight/.test(h))return'/assets/tau-sept.webp';if(/necron|некрон|dynasty/.test(h))return'/assets/trazyn-hero.webp';if(/mechanicus|механикус|titan/.test(h))return'/assets/mechanicus-forge.webp';if(/chaos|хаос|black legion|red corsair|plague|thousand sons/.test(h))return'/assets/great-rift-panorama.webp';return'/assets/imperium-city.jpg'}
 if(type==='arsenal'){const n=(o.name||'').toLowerCase();if(/гаус|warscythe|некрон|blackstone|пилон/.test(n))return'/assets/trazyn-hero.webp';if(/pulse|crisis|тау|t’au|t'au/.test(n))return'/assets/tau-empire.webp';if(/carnifex|bio-titan|тира|био/.test(n))return'/assets/tyranids-war.webp';if(/stompa|орк/.test(n))return'/assets/orks-war.webp';return'/assets/primarchs.jpg';}
 return'/assets/imperium-city.jpg';
}
function mediaFor(type,o){
 const curated=window.MEDIA_LIBRARY?.[type]?.[o.id]||[];
 const hero=assetFor(type,o);
 const contextual=[];
 if(type==='location')contextual.push({src:'/assets/galaxy-atlas.webp',caption:`${o.name} — положение в галактическом атласе`,credit:'Imperium Archive · generated cartography'});
 if(type==='faction'&&o.id==='orks')contextual.push({src:'/assets/orks-war.webp',caption:'Орочья военная культура и Waaagh!',credit:'Imperium Archive · generated concept art'});
 if(type==='faction'&&o.id==='tyranids')contextual.push({src:'/assets/tyranids-war.webp',caption:'Тиранидское вторжение',credit:'Imperium Archive · generated concept art'});
 if(type==='faction'&&o.id==='tau')contextual.push({src:'/assets/tau-empire.webp',caption:'Военные силы Империи Т’ау',credit:'Imperium Archive · generated concept art'});
 const related=findRelations(type,o).slice(0,4).map(([t,id])=>{const r=getRecord(t,id);return r?{src:assetFor(t,r),caption:`Связанная запись: ${r.name}`,credit:'Imperium Archive · визуальная связь архива'}:null}).filter(Boolean);
 const fallback=[{src:hero,caption:`${o.name} — основная иллюстрация`,credit:window.SPECIFIC_ART?.[`${type}:${o.id}`]?'Imperium Archive · generated concept art':'Imperium Archive · тематический резерв'},...contextual,...related];
 const all=[...curated,...fallback],seen=new Set();return all.filter(m=>m?.src&&!seen.has(m.src)&&(seen.add(m.src),true)).slice(0,6);
}
function eventRelations(type,o){const names=[o.name,o.en].filter(Boolean).map(x=>x.toLowerCase());if(type==='character'){const last=o.name.split(/\s+/).pop();if(last&&last.length>4)names.push(last.toLowerCase())}return L.events.filter(ev=>{if((ev.connections||[]).some(x=>x[0]===type&&x[1]===o.id))return true;const hay=JSON.stringify(ev).toLowerCase();return names.some(n=>n.length>4&&hay.includes(n))}).slice(0,10)}
function worldRelations(type,o){const hay=JSON.stringify(o).toLowerCase();return L.locations.filter(w=>(w.connections||[]).some(x=>x[0]===type&&x[1]===o.id)||((type==='legion'||type==='chapter')&&o.home&&o.home.toLowerCase().includes(w.name.toLowerCase()))||(w.name.length>4&&hay.includes(w.name.toLowerCase()))).slice(0,8)}
function sectionText(title,text){return `<section class="detail-block prose-block"><h2>${esc(title)}</h2><p>${esc(text)}</p></section>`}
function autoContext(type,o){
 if(type==='character')return `Запись относится к категории «${o.type||'персонаж'}». Статус: ${o.status||'не указан'}. ${o.era?`Основная эпоха: ${o.era}.`:''} Архив связывает персонажа с легионами, организациями, мирами и войнами, чтобы биография читалась не изолированно, а как часть общей истории галактики.`;
 if(type==='legion')return `${o.name} — ${o.allegiance==='loyalist'?'лояльный':'предательский'} легион эпохи Великого крестового похода. Родной мир или ключевая база: ${o.home||'не указана'}. В архиве легион связан с примархом, известными персонажами, мирами и событиями Ереси Хоруса.`;
 if(type==='chapter')return `${o.name} — орден Адептус Астартес. Основание: ${o.founding||'не установлено'}. ${o.parentLegion?`Генетическая линия восходит к легиону «${byId(L.legions,o.parentLegion)?.name||o.parentLegion}».`:'Происхождение особое, спорное или официально не раскрыто.'} Родной мир / база: ${o.home||'не указана'}. Основная доктрина: ${o.specialty||'универсальная война'}.`; 
 if(type==='location')return `${o.name} расположен в регионе «${o.segmentum||'не указан'}» и классифицирован как «${o.type||'объект'}». Контроль или основная связь: ${o.affiliation||'не определена'}. Значение мира раскрывается через войны и фракции, которые за него сражались.`;
 if(type==='event')return `Событие датируется периодом ${o.date||'не указано'}. Для понимания контекста используй связанные записи: они показывают участников, места и последствия, а не только краткое описание кампании.`;
 if(type==='faction')return `${o.name} относится к группе «${o.group||'не указана'}». Сильные стороны, культура и конфликты фракции лучше всего раскрываются через связанные миры, командиров, организации и войны.`;
 if(type==='organization')return `Организация относится к блоку «${o.group||'не указан'}». Её влияние раскрывается через связанные фигуры, войны и институты.`;
 return `Эта запись входит в категорию «${o.category||'арсенал'}». В 40K техника и оружие почти всегда важны не сами по себе, а как часть доктрины конкретной фракции, эпохи или театра войны.`;
}
function renderRelationCards(rel){return rel.slice(0,12).map(([t,id])=>{const r=getRecord(t,id);if(!r)return'';return `<button class="related-card" data-detail="${t}" data-id="${id}" style="--art:url('${assetFor(t,r)}')"><span>${t}</span><h4>${esc(r.name)}</h4><p>${esc(r.summary||r.tagline||r.title||'Связанная запись архива.')}</p><b>Открыть →</b></button>`}).join('')}
function lineageFlow(type,o){
 const nodes=[];const add=(t,id,role)=>{const r=getRecord(t,id);if(r&&!nodes.some(n=>n.t===t&&n.id===id))nodes.push({t,id,role,r})};
 if(type==='chapter'){const leg=o.parentLegion&&byId(L.legions,o.parentLegion);if(leg?.primarch)add('character',leg.primarch,'ПРИМАРХ');if(leg)add('legion',leg.id,'ЛЕГИОН-ПРЕДОК');add('chapter',o.id,'ОРДЕН');L.characters.filter(c=>c.chapter===o.id).slice(0,3).forEach(c=>add('character',c.id,'ГЕРОЙ ОРДЕНА'));}
 else if(type==='legion'){if(o.primarch)add('character',o.primarch,'ПРИМАРХ');add('legion',o.id,'ЛЕГИОН');L.chapters.filter(c=>c.parentLegion===o.id).slice(0,5).forEach(c=>add('chapter',c.id,'НАСЛЕДНИК'));}
 else if(type==='character'){if(o.legion)add('legion',o.legion,'ЛЕГИОН');if(o.chapter)add('chapter',o.chapter,'ОРДЕН');if(o.faction)add('faction',o.faction,'ФРАКЦИЯ');worldRelations(type,o).slice(0,2).forEach(w=>add('location',w.id,'МИР'));}
 else if(type==='faction'){add('faction',o.id,'ФРАКЦИЯ');L.organizations.filter(x=>(x.connections||[]).some(c=>c[0]==='faction'&&c[1]===o.id)).slice(0,7).forEach(x=>add('organization',x.id,'ПОДФРАКЦИЯ'));}
 if(nodes.length<2)return'';
 return `<section class="detail-block lineage-flow-block"><div class="block-head"><div><p class="eyebrow">ARCHIVE LINEAGE</p><h2>${type==='chapter'||type==='legion'?'Генетическая линия и наследие':'Связи происхождения'}</h2></div><small>Каждый узел — отдельная статья архива</small></div><div class="lineage-flow">${nodes.map((n,i)=>`<button data-detail="${n.t}" data-id="${n.id}"><i style="background-image:url('${assetFor(n.t,n.r)}')"></i><span><small>${n.role}</small><b>${esc(n.r.name)}</b></span>${i<nodes.length-1?'<em>→</em>':''}</button>`).join('')}</div></section>`
}
function renderDetail(type,o){
 const back={character:'characters',legion:'legions',chapter:'chapters',faction:'factions',location:'worlds',event:'timeline',organization:'organizations',arsenal:'arsenal'}[type];
 const names={character:'PERSONAE RECORD',legion:'LEGIONES ASTARTES',chapter:'ADEPTUS ASTARTES / CHAPTER',faction:'BELLIGERENT DOSSIER',location:'ASTROGRAPHICA',event:'CHRONOLOGICA',organization:'ORDINES / INSTITUTION',arsenal:'ARSENAL / MACHINA'};
 const ex=expFor(type,o),hero=assetFor(type,o),rel=findRelations(type,o),evs=eventRelations(type,o),worlds=worldRelations(type,o);
 let watermark='✠',meta=[];
 if(type==='character'){watermark=o.legion?(byId(L.legions,o.legion)?.n||'☠'):'☠';meta=[o.type,o.title,o.status,o.era]}
 if(type==='legion'){watermark=o.n;meta=[`Легион ${o.n}`,o.allegiance==='loyalist'?'Лоялист':'Предатель',`Родной мир: ${o.home}`]}
 if(type==='chapter'){watermark='✙';meta=[o.founding,o.parentLegion?`Генолиния: ${byId(L.legions,o.parentLegion)?.name||o.parentLegion}`:'Происхождение: особое / неизвестное',`База: ${o.home||'не указана'}`,o.specialty]}
 if(type==='faction'){watermark=o.icon;meta=[o.group,o.en]}
 if(type==='location'){watermark='✦';meta=[o.segmentum,o.type,o.affiliation]}
 if(type==='event'){watermark='⌛';meta=[o.date]}
 if(type==='organization'){watermark='⌘';meta=[o.group]}
 if(type==='arsenal'){watermark='⚙';meta=[o.category]}
 const history=(o.history||[]).map(x=>`<div class="history-item">${esc(x)}</div>`).join('');
 const facts=(o.facts||o.knownFor||[]).map(x=>`<li>${esc(x)}</li>`).join('');
 const extraSections=(ex?.sections||[]).map(([h,t],i)=>`<section class="detail-block prose-block lore-section" id="lore-${i}"><h2>${esc(h)}</h2><p>${esc(t)}</p></section>`).join('');
 const fallbackOverview=(!extraSections)?sectionText('Архивный обзор',o.summary||o.tagline||autoContext(type,o)):'';
 const reading=(ex?.reading||[]);
 const gallery=mediaFor(type,o);
 document.getElementById('detailPage').innerHTML=`
 <div class="detail-breadcrumb"><button data-route="${back}">← ${labels[back]}</button><span>/</span><span>${esc(o.name)}</span></div>
 <section class="detail-cinematic" style="--hero:url('${hero}')" data-watermark="${esc(watermark)}">
   <div class="detail-cinematic-shade"></div><div class="detail-cinematic-copy"><span class="detail-kicker">${names[type]}</span><h1>${esc(o.name)}</h1><p>${esc(ex?.subtitle||o.title||o.tagline||o.summary||'')}</p><div class="detail-meta">${meta.filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('')}</div></div>
 </section>
 <nav class="detail-tabs"><a href="#overview">Обзор</a><a href="#history">История</a><a href="#relations">Связи</a><a href="#gallery">Галерея</a><a href="#sources">Источники</a></nav><div class="detail-actions"><button data-bookmark="${type}:${o.id}">☆ В избранное</button><button data-copy-link>⧉ Скопировать ссылку</button><span>Запись связана: ${rel.length} · события: ${evs.length} · миры: ${worlds.length}</span></div>
 <div class="detail-grid"><main class="detail-main">
   <section class="detail-block intro-block" id="overview"><div><p class="eyebrow">ARCHIVE SUMMARY</p><h2>${type==='character'?'Кто это и почему важен':'Контекст записи'}</h2><p class="intro-copy">${esc(o.summary||o.tagline||autoContext(type,o))}</p><p>${esc(autoContext(type,o))}</p></div><div class="dossier-seal">${esc(watermark)}</div></section>
   ${type==='chapter'?`<section class="detail-block chapter-lineage-block"><div><p class="eyebrow">GENE-SEED / HERALDRY</p><h2>Генетическая линия и доктрина</h2><p>${esc(o.parentLegion?`Орден ведёт генетическую линию от ${byId(L.legions,o.parentLegion)?.name||o.parentLegion}. Основание: ${o.founding}.`:`Происхождение ордена имеет особый статус, спорно или не раскрыто в имперских записях. Основание: ${o.founding}.`)}</p></div><div class="chapter-heraldry" style="--c1:${esc(o.colors?.[0]||'#c5a24a')};--c2:${esc(o.colors?.[1]||'#151515')}"><i></i><b>✙</b></div><div class="chapter-specs"><span><small>База</small><b>${esc(o.home||'—')}</b></span><span><small>Командующий</small><b>${esc(o.master||'—')}</b></span><span><small>Доктрина</small><b>${esc(o.specialty||'—')}</b></span></div></section>`:''}
   ${lineageFlow(type,o)}
   ${extraSections}${fallbackOverview}
   ${history?`<section class="detail-block" id="history"><p class="eyebrow">CHRONOLOGY / RECORD</p><h2>История и этапы</h2><div class="history-stack">${history}</div></section>`:''}
   ${facts?`<section class="detail-block"><p class="eyebrow">KEY DATA</p><h2>Ключевые факты</h2><ul class="fact-list">${facts}</ul></section>`:''}
   ${evs.length?`<section class="detail-block" id="relations"><div class="block-head"><div><p class="eyebrow">CONNECTED EVENTS</p><h2>События и кампании</h2></div></div><div class="event-strip">${evs.map(e=>`<button data-detail="event" data-id="${e.id}"><small>${esc(e.date)}</small><b>${esc(e.name)}</b><span>${esc(e.summary)}</span></button>`).join('')}</div></section>`:''}
   ${type==='legion'&&(L.chapters||[]).some(c=>c.parentLegion===o.id)?`<section class="detail-block successor-block"><p class="eyebrow">GENE-LINE DESCENDANTS</p><h2>Ордена-наследники</h2><p>После Ереси генетическое наследие легиона продолжилось в самостоятельных орденах. Ниже — записи архива, напрямую связанные с этой линией.</p><div class="successor-strip">${L.chapters.filter(c=>c.parentLegion===o.id).slice(0,18).map(c=>`<button data-detail="chapter" data-id="${c.id}"><i style="--c1:${c.colors?.[0]||'#c5a24a'};--c2:${c.colors?.[1]||'#171717'}"></i><span><b>${esc(c.name)}</b><small>${esc(c.founding)}</small></span></button>`).join('')}</div></section>`:''}
   ${rel.length?`<section class="detail-block"><p class="eyebrow">RELATION GRAPH</p><h2>Связанные записи</h2><div class="related-grid">${renderRelationCards(rel)}</div></section>`:''}
   <section class="detail-block gallery-block" id="gallery"><div class="block-head"><div><p class="eyebrow">VISUAL ARCHIVE</p><h2>Иллюстративные материалы</h2></div><small>Изображения ставятся по смыслу. Для внешних материалов источник указан прямо под изображением.</small></div><div class="detail-gallery">${gallery.map((g,i)=>`<figure class="media-figure"><img data-lightbox src="${esc(g.src)}" alt="${esc(o.name)} — ${esc(g.caption||`иллюстрация ${i+1}`)}" loading="lazy" onerror="this.closest('figure').classList.add('media-error')"><figcaption><b>${esc(g.caption||o.name)}</b><small>${esc(g.credit||'Imperium Archive')}</small>${g.source?`<a href="${esc(g.source)}" target="_blank" rel="noreferrer">Источник ↗</a>`:''}</figcaption></figure>`).join('')}</div></section>
   ${reading.length?`<section class="detail-block reading-block"><p class="eyebrow">FURTHER READING</p><h2>Что читать дальше</h2><div class="reading-grid">${reading.map((r,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span><b>${esc(r)}</b><small>Рекомендуемый материал по теме</small></article>`).join('')}</div></section>`:''}
 </main><aside class="detail-aside">
   <section class="detail-block dossier"><p class="eyebrow">DOSSIER</p><h2>Краткая карточка</h2>${meta.filter(Boolean).map((x,i)=>`<div class="dossier-row"><span>${['Тип / статус','Принадлежность','Эпоха / регион','Дополнительно'][i]||'Данные'}</span><b>${esc(x)}</b></div>`).join('')}${worlds.length?`<div class="dossier-row"><span>Связанные миры</span><b>${worlds.length}</b></div>`:''}${evs.length?`<div class="dossier-row"><span>Связанные события</span><b>${evs.length}</b></div>`:''}</section>
   ${worlds.length?`<section class="detail-block"><h2>Миры и регионы</h2><div class="relation-list">${relationLinks(worlds.map(w=>['location',w.id,w.name]))}</div></section>`:''}
   ${rel.length?`<section class="detail-block"><h2>Быстрые переходы</h2><div class="relation-list">${relationLinks(rel.slice(0,10))}</div></section>`:''}
   <section class="detail-block" id="sources"><h2>Источники и проверка</h2><div class="source-list">${sourceLinks(o.sources||[])}</div><p class="source-note">Текст написан как авторский пересказ и навигационный конспект. Где канон менялся между редакциями или намеренно неоднозначен, лучше сверяться с актуальными кодексами, Black Library, Warhammer Community и указанными энциклопедиями.</p></section>
 </aside></div>`;
}

function renderHome(){
 const stats=[['Персонажи',L.characters.length,'characters'],['Фракции',L.factions.length,'factions'],['Легионы',L.legions.length,'legions'],['Ордена',L.chapters.length,'chapters'],['Миры и регионы',L.locations.length,'worlds'],['События',L.events.length,'timeline'],['Организации',L.organizations.length,'organizations'],['Арсенал',L.arsenal.length,'arsenal']];
 document.getElementById('statsRibbon').innerHTML=stats.map(([n,v,r])=>`<button data-route="${r}"><strong>${v}</strong><span>${n}</span></button>`).join('');
 const modules=[['map','✥','ASTROGRAPHICA','Карта галактики',`${L.locations.length} миров, регионов и аномалий, панорамирование, масштаб и фильтры контроля.`],['characters','☠','PERSONAE','Персонажи','Примархи, герои, ксеносы, лорды Хаоса и командиры с перекрёстными ссылками.'],['factions','⚔','BELLIGERENTS','Фракции','Империум, Хаос, Аэльдари, Некроны, Тираниды, Т’ау и другие силы.'],['legions','♜','LEGIONES','Легионы','Все 18 известных легионов Астартес, их примархи, миры и наследие.'],['chapters','✙','CHAPTERS','Ордена Астартес',`${L.chapters.length} орденов, генолинии, Основания, геральдика, герои и войны.`],['worlds','◉','MUNDI','Миры и регионы','Миры-крепости, кузницы, ульи, аномалии и планеты орденов.'],['organizations','⌘','ORDINES','Организации','Инквизиция, ордосы, династии, культы, ордены и институты.'],['arsenal','⚙','ARSENAL','Техника и оружие','Болтеры, броня, танки, дредноуты, титаны, корабли и ксенотехнологии.'],['timeline','⌛','CHRONOLOGICA','Хронология','От Войн Объединения до Четвёртой Тиранидской войны.']];
 document.getElementById('moduleGrid').innerHTML=modules.map(([r,ic,k,h,p],i)=>`<button class="module-card" data-route="${r}"><b class="module-icon">${ic}</b><span>${k}</span><h3>${h}</h3><p>${p}</p><i>${String(i+1).padStart(2,'0')}</i></button>`).join('');
 const items=[['character','guilliman'],['character','lion'],['character','abaddon'],['location','cadia'],['location','pariah-nexus'],['organization','black-legion']];
 document.getElementById('homeSpotlight').innerHTML=items.map(([t,id])=>{const o=getRecord(t,id);return o?`<button class="spot-card" data-detail="${t}" data-id="${id}"><span>${t.toUpperCase()}</span><h3>${esc(o.name)}</h3><p>${esc(o.summary)}</p><b>Открыть досье →</b></button>`:''}).join('');
 document.getElementById('randomRecord').onclick=()=>{const types=Object.keys(collections),t=types[Math.floor(Math.random()*types.length)],a=collections[t],o=a[Math.floor(Math.random()*a.length)];openDetail(t,o.id)};
}

let factionGroup='all';
function renderFactions(q=''){q=q.toLowerCase();document.getElementById('factionGrid').innerHTML=L.factions.filter(f=>(factionGroup==='all'||f.group===factionGroup)&&JSON.stringify(f).toLowerCase().includes(q)).map(f=>`<button class="archive-card illustrated" data-detail="faction" data-id="${f.id}"><div class="card-art" style="background-image:linear-gradient(180deg,transparent,#0c0d0e),url('${assetFor('faction',f)}')"></div><div class="sigil">${f.icon}</div><span class="meta">${f.group} · ${esc(f.en)}</span><h3>${esc(f.name)}</h3><p>${esc(f.tagline)}</p><b>Открыть →</b></button>`).join('')}
document.getElementById('factionSearch').addEventListener('input',e=>renderFactions(e.target.value));document.querySelectorAll('[data-fgroup]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-fgroup]').forEach(x=>x.classList.remove('active'));b.classList.add('active');factionGroup=b.dataset.fgroup;renderFactions(document.getElementById('factionSearch').value)}));
function renderLegions(filter='all'){document.getElementById('legionGrid').innerHTML=L.legions.filter(l=>filter==='all'||l.allegiance===filter).map(l=>`<button class="legion-card ${l.allegiance} illustrated" data-detail="legion" data-id="${l.id}"><div class="card-art" style="background-image:linear-gradient(180deg,transparent,#0c0d0e),url('${assetFor('legion',l)}')"></div><span class="roman">${l.n}</span><span class="meta">${l.allegiance==='loyalist'?'LOYALIST':'TRAITOR'} · ${esc(l.home)}</span><h3>${esc(l.name)}</h3><p>${esc(l.summary)}</p><b>Примарх: ${esc(byId(L.characters,l.primarch)?.name||'не указан')}</b></button>`).join('')}
document.querySelectorAll('[data-loyalty]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-loyalty]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLegions(b.dataset.loyalty)}));
let chapterLegion='all',chapterFounding='all';
function chapterCrest(c){const initials=(c.en||c.name).split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();return `<div class="chapter-crest" style="--c1:${esc(c.colors?.[0]||'#b89545')};--c2:${esc(c.colors?.[1]||'#151515')}"><i></i><b>${esc(initials||'✙')}</b></div>`}
function initChapterFilters(){const lsel=document.getElementById('chapterLegionFilter'),fsel=document.getElementById('chapterFoundingFilter');if(!lsel||lsel.dataset.ready)return;lsel.dataset.ready='1';const parents=[...new Set(L.chapters.map(c=>c.parentLegion).filter(Boolean))];lsel.innerHTML='<option value="all">Все генолинии</option>'+parents.map(id=>`<option value="${id}">${esc(byId(L.legions,id)?.name||id)}</option>`).join('')+'<option value="unknown">Особое / неизвестное происхождение</option>';const fs=[...new Set(L.chapters.map(c=>c.founding).filter(Boolean))].sort();fsel.innerHTML='<option value="all">Все Основания</option>'+fs.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');const lineage=document.getElementById('geneLineage');lineage.innerHTML=L.legions.filter(l=>l.allegiance==='loyalist').map(l=>`<button data-chapter-lineage="${l.id}" style="--line:${assetFor('legion',l)}"><span>${l.n}</span><b>${esc(l.name)}</b><small>${L.chapters.filter(c=>c.parentLegion===l.id).length} записей</small></button>`).join('')+`<button data-chapter-lineage="unknown"><span>?</span><b>Неизвестные линии</b><small>${L.chapters.filter(c=>!c.parentLegion).length} записей</small></button>`;lineage.querySelectorAll('[data-chapter-lineage]').forEach(b=>b.onclick=()=>{chapterLegion=b.dataset.chapterLineage;lsel.value=chapterLegion;renderChapters(document.getElementById('chapterSearch').value)});lsel.onchange=()=>{chapterLegion=lsel.value;renderChapters(document.getElementById('chapterSearch').value)};fsel.onchange=()=>{chapterFounding=fsel.value;renderChapters(document.getElementById('chapterSearch').value)};document.getElementById('chapterSearch').oninput=e=>renderChapters(e.target.value)}
function renderChapters(q=''){initChapterFilters();q=q.toLowerCase();const arr=L.chapters.filter(c=>(chapterLegion==='all'||(chapterLegion==='unknown'?!c.parentLegion:c.parentLegion===chapterLegion))&&(chapterFounding==='all'||c.founding===chapterFounding)&&JSON.stringify(c).toLowerCase().includes(q));document.getElementById('chapterCount').textContent=`Показано: ${arr.length} / ${L.chapters.length}`;document.getElementById('chapterGrid').innerHTML=arr.map(c=>`<button class="chapter-card illustrated" data-detail="chapter" data-id="${c.id}"><div class="card-art" style="background-image:linear-gradient(180deg,transparent,#0b0d0e),url('${assetFor('chapter',c)}')"></div>${chapterCrest(c)}<div class="chapter-card-copy"><span class="meta">${esc(c.founding)} · ${esc(c.parentLegion?byId(L.legions,c.parentLegion)?.name||c.parentLegion:'GENE-SEED UNKNOWN')}</span><h3>${esc(c.name)}</h3><p>${esc(c.summary)}</p><div class="chapter-card-data"><span>${esc(c.home||'База неизвестна')}</span><span>${esc(c.specialty||'Универсальная война')}</span></div><b>Открыть досье →</b></div></button>`).join('')}
let worldAff='all',worldType='all';
function initWorldFilters(){const t=document.getElementById('worldTypeFilter');if(!t||t.dataset.ready)return;t.dataset.ready='1';const types=[...new Set(L.locations.map(x=>x.type).filter(Boolean))].sort();t.innerHTML='<option value="all">Все типы</option>'+types.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');document.getElementById('worldAffFilter').onchange=e=>{worldAff=e.target.value;renderWorlds(document.getElementById('worldSearch').value)};t.onchange=e=>{worldType=e.target.value;renderWorlds(document.getElementById('worldSearch').value)};document.getElementById('worldSearch').oninput=e=>renderWorlds(e.target.value)}
function renderWorlds(q=''){initWorldFilters();q=q.toLowerCase();const arr=L.locations.filter(w=>(worldAff==='all'||w.affiliation===worldAff||(w.factions||[]).includes(worldAff))&&(worldType==='all'||w.type===worldType)&&JSON.stringify(w).toLowerCase().includes(q));document.getElementById('worldCount').textContent=`Показано: ${arr.length} / ${L.locations.length}`;document.getElementById('worldGrid').innerHTML=arr.map(w=>`<button class="world-card illustrated" data-detail="location" data-id="${w.id}"><div class="card-art" style="background-image:linear-gradient(180deg,transparent,#0b0d0e),url('${assetFor('location',w)}')"></div><div class="world-card-copy"><span class="meta">${esc(w.segmentum||'Неизвестный регион')} · ${esc(w.type||'объект')}</span><h3>${esc(w.name)}</h3><p>${esc(w.summary)}</p><div><small>Контроль / связь</small><b>${esc(w.affiliation||'не определено')}</b></div></div></button>`).join('')}
function renderCharacters(q=''){q=q.toLowerCase();document.getElementById('characterGrid').innerHTML=L.characters.filter(c=>JSON.stringify(c).toLowerCase().includes(q)).map(c=>`<button class="character-card illustrated" data-detail="character" data-id="${c.id}"><div class="card-art" style="background-image:linear-gradient(180deg,transparent,#0c0d0e),url('${assetFor('character',c)}')"></div><span class="type-badge">${esc(c.type)}</span><h3>${esc(c.name)}</h3><div class="meta">${esc(c.title)} · ${esc(c.status)}</div><p>${esc(c.summary)}</p><span class="arrow">→</span></button>`).join('')}
document.getElementById('characterSearch').addEventListener('input',e=>renderCharacters(e.target.value));
function renderOrganizations(q=''){q=q.toLowerCase();document.getElementById('organizationGrid').innerHTML=L.organizations.filter(o=>JSON.stringify(o).toLowerCase().includes(q)).map(o=>`<button class="archive-card org-card illustrated" data-detail="organization" data-id="${o.id}"><div class="card-art" style="background-image:linear-gradient(180deg,transparent,#0c0d0e),url('${assetFor('organization',o)}')"></div><div class="sigil">⌘</div><span class="meta">${esc(o.group)}</span><h3>${esc(o.name)}</h3><p>${esc(o.summary)}</p><b>Открыть →</b></button>`).join('')}
document.getElementById('organizationSearch').addEventListener('input',e=>renderOrganizations(e.target.value));
let arsenalCat='all';
function initArsenalTabs(){const cats=[...new Set(L.arsenal.map(x=>x.category))];document.getElementById('arsenalTabs').innerHTML=['all',...cats].map(c=>`<button class="chip ${c==='all'?'active':''}" data-acat="${esc(c)}">${c==='all'?'Все':esc(c)}</button>`).join('');document.querySelectorAll('[data-acat]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-acat]').forEach(x=>x.classList.remove('active'));b.classList.add('active');arsenalCat=b.dataset.acat;renderArsenal(document.getElementById('arsenalSearch').value)}))}
function renderArsenal(q=''){q=q.toLowerCase();document.getElementById('arsenalGrid').innerHTML=L.arsenal.filter(o=>(arsenalCat==='all'||o.category===arsenalCat)&&JSON.stringify(o).toLowerCase().includes(q)).map(o=>`<button class="archive-card arsenal-card illustrated" data-detail="arsenal" data-id="${o.id}"><div class="card-art" style="background-image:linear-gradient(180deg,transparent,#0c0d0e),url('${assetFor('arsenal',o)}')"></div><div class="sigil">⚙</div><span class="meta">${esc(o.category)}</span><h3>${esc(o.name)}</h3><p>${esc(o.summary)}</p><b>Открыть →</b></button>`).join('')}
document.getElementById('arsenalSearch').addEventListener('input',e=>renderArsenal(e.target.value));
function renderTimeline(){document.getElementById('timelineList').innerHTML=L.events.map(e=>`<article><time>${esc(e.date)}</time><button class="timeline-card illustrated" data-detail="event" data-id="${e.id}"><div class="timeline-thumb card-art" style="background-image:linear-gradient(90deg,transparent,#111315),url('${assetFor('event',e)}')"></div><div class="timeline-copy"><h3>${esc(e.name)}</h3><p>${esc(e.summary)}</p><b>Открыть запись →</b></div></button></article>`).join('')}

// Map
const pointRoot=document.getElementById('mapPoints');
function mapColorAff(p){if(p.affiliation==='imperium')return'imperium';if(p.affiliation==='chaos')return'chaos';if(['tau','aeldari','drukhari','necrons','orks','tyranids'].includes(p.affiliation))return p.affiliation;return'contested'}
function renderMapPoints(){const sel=document.getElementById('mapTypeFilter'),names={world:'Миры',forge:'Миры-кузницы',hive:'Миры-ульи',craftworld:'Миры-корабли',region:'Регионы',sector:'Сектора',anomaly:'Аномалии',destroyed:'Уничтоженные миры',station:'Станции / крепости',site:'Места сражений',tomb:'Миры-гробницы',shrine:'Святые миры',deathworld:'Миры смерти',desert:'Пустынные миры',ice:'Ледяные миры',daemon:'Демон-миры',ruin:'Руины',webway:'Паутина'};if(sel&&!sel.dataset.dynamic){sel.dataset.dynamic='1';sel.innerHTML='<option value="all">Все типы</option>'+[...new Set(L.locations.map(x=>x.type).filter(Boolean))].sort().map(t=>`<option value="${esc(t)}">${esc(names[t]||t)}</option>`).join('')}const critical=new Set(['terra','cadia','macragge','baal','armageddon','eye-of-terror','pariah-nexus','tau','commorragh','ulthwe','vigilus']);pointRoot.innerHTML=L.locations.map(p=>`<button class="map-point ${critical.has(p.id)?'critical':''}" style="--x:${p.x};--y:${p.y}" data-id="${p.id}" data-affiliation="${mapColorAff(p)}" data-type="${p.type}" title="${esc(p.name)}"><i></i><span>${esc(p.name)}</span></button>`).join('');pointRoot.querySelectorAll('.map-point').forEach(b=>b.addEventListener('click',()=>selectMapRecord(b.dataset.id)));applyMapFilters()}
function selectMapRecord(id){const p=byId(L.locations,id);if(!p)return;pointRoot.querySelectorAll('.map-point').forEach(x=>x.classList.toggle('highlight',x.dataset.id===id));document.getElementById('mapSide').innerHTML=`<p class="eyebrow">ASTROGRAPHICA RECORD</p><h3>${esc(p.name)}</h3><p>${esc(p.summary)}</p><div class="record-meta"><div><span>Сегментум / зона</span><b>${esc(p.segmentum)}</b></div><div><span>Тип</span><b>${esc(p.type)}</b></div><div><span>Контроль</span><b>${esc(p.affiliation)}</b></div></div><p>${esc(p.importance||'')}</p><button class="detail-open" data-detail="location" data-id="${p.id}">Открыть полную запись →</button>`}
function applyMapFilters(){const q=document.getElementById('mapSearch').value.toLowerCase(),f=document.getElementById('mapFactionFilter').value,t=document.getElementById('mapTypeFilter').value,labelsOn=document.getElementById('toggleLabels').checked;pointRoot.querySelectorAll('.map-point').forEach(el=>{const p=byId(L.locations,el.dataset.id);const matchQ=!q||JSON.stringify(p).toLowerCase().includes(q);const matchF=f==='all'||mapColorAff(p)===f||p.affiliation===f||(p.factions||[]).includes(f);const matchT=t==='all'||p.type===t;el.classList.toggle('hidden',!(matchQ&&matchF&&matchT));el.querySelector('span').style.display=labelsOn?'':'none'})}
['mapSearch','mapFactionFilter','mapTypeFilter','toggleLabels'].forEach(id=>document.getElementById(id).addEventListener(id==='mapSearch'?'input':'change',applyMapFilters));document.getElementById('toggleRift').addEventListener('change',e=>document.getElementById('greatRift').style.display=e.target.checked?'':'none');document.getElementById('toggleTerritories').addEventListener('change',e=>document.querySelectorAll('[data-territory]').forEach(x=>x.style.display=e.target.checked?'':'none'));
const viewport=document.getElementById('galaxyViewport'),stage=document.getElementById('galaxyStage');let mapState={scale:.8,x:0,y:0},drag=null;
function fitMap(){const r=viewport.getBoundingClientRect();if(!r.width)return;mapState.scale=Math.min(r.width/1200,r.height/780);mapState.x=(r.width-1200*mapState.scale)/2;mapState.y=(r.height-780*mapState.scale)/2;updateMapTransform()}
function updateMapTransform(){stage.style.transform=`translate(${mapState.x}px,${mapState.y}px) scale(${mapState.scale})`}
function zoomMap(delta,cx=viewport.clientWidth/2,cy=viewport.clientHeight/2){const old=mapState.scale,next=Math.max(.4,Math.min(3,old*delta)),wx=(cx-mapState.x)/old,wy=(cy-mapState.y)/old;mapState.scale=next;mapState.x=cx-wx*next;mapState.y=cy-wy*next;updateMapTransform()}
document.getElementById('zoomIn').onclick=()=>zoomMap(1.18);document.getElementById('zoomOut').onclick=()=>zoomMap(.85);document.getElementById('zoomReset').onclick=fitMap;viewport.addEventListener('wheel',e=>{e.preventDefault();const r=viewport.getBoundingClientRect();zoomMap(e.deltaY<0?1.12:.89,e.clientX-r.left,e.clientY-r.top)},{passive:false});viewport.addEventListener('pointerdown',e=>{if(e.target.closest('.map-point'))return;drag={x:e.clientX,y:e.clientY,mx:mapState.x,my:mapState.y};viewport.setPointerCapture(e.pointerId);viewport.classList.add('dragging')});viewport.addEventListener('pointermove',e=>{if(!drag)return;mapState.x=drag.mx+(e.clientX-drag.x);mapState.y=drag.my+(e.clientY-drag.y);updateMapTransform()});viewport.addEventListener('pointerup',()=>{drag=null;viewport.classList.remove('dragging')});window.addEventListener('resize',()=>{if(document.getElementById('map').classList.contains('active-page'))fitMap()});

// Global search
const searchOverlay=document.getElementById('globalSearch'),searchInput=document.getElementById('globalSearchInput');
function openGlobalSearch(){searchOverlay.classList.add('open');searchInput.value='';renderGlobalResults('');setTimeout(()=>searchInput.focus(),40)}function closeGlobalSearch(){searchOverlay.classList.remove('open')}
document.getElementById('globalSearchBtn').onclick=openGlobalSearch;document.getElementById('closeGlobalSearch').onclick=closeGlobalSearch;searchOverlay.addEventListener('click',e=>{if(e.target===searchOverlay)closeGlobalSearch()});
function searchRecords(q){q=q.toLowerCase().trim();const out=[];Object.entries(collections).forEach(([type,arr])=>arr.forEach(o=>{if(!q||JSON.stringify(o).toLowerCase().includes(q))out.push({type,o})}));return out.slice(0,40)}
function renderGlobalResults(q){document.getElementById('globalSearchResults').innerHTML=searchRecords(q).map(({type,o})=>`<button class="global-result" data-detail="${type}" data-id="${o.id}"><span><b>${esc(o.name)}</b><small>${type} · ${esc(o.title||o.en||o.date||o.segmentum||o.home||o.category||o.group||'')}</small></span><strong>→</strong></button>`).join('')}
searchInput.addEventListener('input',e=>renderGlobalResults(e.target.value));document.getElementById('globalSearchResults').addEventListener('click',()=>closeGlobalSearch());document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openGlobalSearch()}if(e.key==='Escape'){closeGlobalSearch();closeAssistant()}});

// AI
const panel=document.getElementById('assistantPanel'),backdrop=document.getElementById('assistantBackdrop');
function openAssistant(){panel.classList.add('open');backdrop.classList.add('open');setTimeout(()=>document.getElementById('question').focus(),80)}function closeAssistant(){panel.classList.remove('open');backdrop.classList.remove('open')}
document.getElementById('openAssistant').onclick=openAssistant;document.getElementById('heroAsk').onclick=openAssistant;document.getElementById('homeAsk2').onclick=openAssistant;document.getElementById('closeAssistant').onclick=closeAssistant;backdrop.onclick=closeAssistant;
function localCommand(text){const t=text.toLowerCase();if(/(открой|покажи|перенеси|перейди|найди)/.test(t)){for(const [type,arr] of Object.entries(collections)){const hit=arr.find(o=>t.includes(o.name.toLowerCase())||(o.en&&t.includes(o.en.toLowerCase())));if(hit)return{kind:'detail',type,id:hit.id,name:hit.name}}const rs=[[/(карт|галактик)/,'map'],[/фракц/,'factions'],[/легион/,'legions'],[/(орден|chapter|наследник)/,'chapters'],[/(мир|планет|регион)/,'worlds'],[/персонаж/,'characters'],[/(организац|ордос|инквизиц)/,'organizations'],[/(оруж|техник|арсенал|титан)/,'arsenal'],[/(хронолог|событ|войн)/,'timeline'],[/(главн|домой)/,'home']];for(const [re,r] of rs)if(re.test(t))return{kind:'route',route:r}}return null}
function addMessage(type,text,sources=[]){const box=document.createElement('div');box.className='msg '+type;box.innerHTML=`<b>${type==='user'?'INQUISITOR':'ASTARTES-AI'}</b><p></p>`;box.querySelector('p').textContent=text;if(sources.length){const s=document.createElement('div');s.className='sources';sources.slice(0,5).forEach(src=>{const a=document.createElement('a');a.href=src.url;a.target='_blank';a.rel='noreferrer';a.textContent=src.title||src.url;s.appendChild(a)});box.appendChild(s)}document.getElementById('chat').appendChild(box);box.scrollIntoView({behavior:'smooth',block:'end'});return box}
function localLoreAnswer(text){
 const q=text.toLowerCase().trim();
 let best=null,bestScore=0;
 for(const [type,arr] of Object.entries(collections))for(const o of arr){
   const hay=[o.name,o.en,o.title,o.summary,o.tagline,...(o.history||[]),...(o.facts||[]),...(o.knownFor||[])].filter(Boolean).join(' ').toLowerCase();
   let score=0;
   for(const token of q.split(/\s+/).filter(x=>x.length>2))if(hay.includes(token))score++;
   if(o.name.toLowerCase().includes(q))score+=8;
   if(score>bestScore){bestScore=score;best={type,o}}
 }
 if(best&&bestScore>0){
   const ex=expFor(best.type,best.o);const extra=ex?.sections?.[0]?.[1];
   const answer=[best.o.summary||best.o.tagline,extra].filter(Boolean).join('\n\n');
   return{answer:answer||`В архиве есть запись «${best.o.name}».`,target:best};
 }
 if(/(кто такой|кто такая)/.test(q))return{answer:'В локальной базе я не нашёл точного совпадения. Попробуй написать имя без лишних слов или воспользоваться глобальным поиском Ctrl+K.'};
 return{answer:'Сейчас Astartes-AI работает как локальная заглушка. Я могу открыть раздел, найти существующую запись и показать краткое описание из базы. Попробуй: «открой Кадию», «кто такой Тразин», «покажи легионы», «что такое Пария Нексус».'};
}
function ask(text){text=text.trim();if(!text)return;addMessage('user',text);const cmd=localCommand(text);if(cmd){if(cmd.kind==='detail'){openDetail(cmd.type,cmd.id);const o=getRecord(cmd.type,cmd.id),ex=o&&expFor(cmd.type,o);addMessage('ai',`${o?.summary||`Открываю запись: ${cmd.name}.`}${ex?.sections?.[0]?.[1]?`\n\n${ex.sections[0][1]}`:''}`)}else{setRoute(cmd.route);addMessage('ai',`Открываю раздел «${labels[cmd.route]}». В локальном режиме я умею навигировать по всему архиву.`)}return}const r=localLoreAnswer(text);addMessage('ai',r.answer);if(r.target){const {type,o}=r.target;setTimeout(()=>{addMessage('ai',`Нашёл связанную запись «${o.name}». Могу открыть её по команде «открой ${o.name}».`)},120)}}

document.getElementById('askForm').addEventListener('submit',e=>{e.preventDefault();const q=document.getElementById('question');ask(q.value);q.value=''});document.getElementById('question').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();document.getElementById('askForm').requestSubmit()}});document.querySelectorAll('.quick-asks button').forEach(b=>b.onclick=()=>ask(b.textContent));

// stars
const canvas=document.getElementById('stars'),ctx=canvas.getContext('2d');let stars=[];function resizeStars(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);stars=Array.from({length:Math.min(220,Math.floor(innerWidth/6))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()+.1,a:Math.random()*.42+.06}))}function drawStars(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#e8dfca';for(const s of stars){ctx.globalAlpha=s.a;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}requestAnimationFrame(drawStars)}

renderHome();renderFactions();renderLegions();renderChapters();renderWorlds();renderCharacters();renderOrganizations();initArsenalTabs();renderArsenal();renderTimeline();renderMapPoints();resizeStars();drawStars();parseHash();setTimeout(fitMap,80);
